version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - bodyclose
    - misspell
    - staticcheck
    - unused
    - ineffassign
  exclusions:
    rules:
      - path: '(.+)_test\.go$'
        linters:
          - errcheck

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
  skip-dirs-use-default: true
