apiVersion: v2
name: unimock
description: A Helm chart for Unimock HTTP mock server
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - mock
  - http
  - testing
maintainers:
  - name: Unimock Team 
