# Simple Examples - Copy and modify these for your use case

# Example 1: Basic REST API (most common)
sections:
  users:
    path_pattern: "/api/users/*"
    body_id_paths: ["/id"]
    header_id_names: ["X-User-ID"]

# Example 2: E-commerce API
sections:
  products:
    path_pattern: "/products/*" 
    body_id_paths: ["/sku", "/product_id"]
  
  orders:
    path_pattern: "/orders/*"
    body_id_paths: ["/order_id"]
    header_id_names: ["X-Order-ID"]

# Example 3: XML Service
sections:
  documents:
    path_pattern: "/api/docs/*"
    body_id_paths: ["/document/id", "//id"]  # XPath syntax

# Example 4: Nested Resources  
sections:
  user_posts:
    path_pattern: "/users/*/posts/*"
    body_id_paths: ["/post_id"]

# Example 5: With Test Scenarios
sections:
  users:
    path_pattern: "/api/users/*"
    body_id_paths: ["/id"]

scenarios:
  - uuid: "user-not-found"
    method: "GET" 
    path: "/api/users/999"
    status_code: 404
    content_type: "application/json"
    data: '{"error": "User not found"}'