name: Push

on:
  push:

jobs:
  test:
    name: Push tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.22', '1.23', '1.24' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run lint
      uses: golangci/golangci-lint-action@v8

    - name: Run unit tests
      run: |
        make install-gotestsum
        make test-unit
