name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true

    - name: Install linter
      run: |
        go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6

    - name: Run Checks
      run: make check

    - name: Run e2e tests
      run: make test-e2e
