apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unimock.fullname" . }}-config
  labels:
    {{- include "unimock.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ .Values.config.yaml | indent 4 }} 
